config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # ルートパスをtasksコントローラーのindexアクションに設定
  root "tasks#index"

  resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      put :complete 
    end

    collection do
      get :past_tasks
      delete :destroy_by_date
    end
    
  end

  resource :settings, only: [:index, :show, :edit, :update]
  resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_setting

  private

  def set_setting
    @setting = Setting.first 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]


  def new
    @comment = Comment.new(date: params[:date])
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to past_tasks_tasks_path,notice: 'コメントを更新しました'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @comment.update(comment_params)
      redirect_to past_tasks_tasks_path
    else
      render :edit
    end
  end


  def destroy
    date = @comment.date
    @comment.destroy
    redirect_to past_tasks_tasks_path
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:comment, :date)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
    before_action :set_setting, only: [:show, :edit, :update]

    def index
        @setting = Setting.first || Setting.create
    end

    def show
    end

    def edit
    end

    def update
        if @setting.update(setting_params)
            redirect_to settings_path, notice: '設定が更新されました。'
          else
            render :edit
          end
    end

    private
    
    def setting_params
        params.require(:setting).permit(:reward_url1, :reward_url2, :reward_url3, :reward_url4, :reward_url5, :reward_url6, :reward_url7, :reward_url8, :reward_url9, :reward_url10, :show_uncompleted_todos, :display_background)
    end

    def set_setting
        @setting = Setting.first || Setting.create
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:edit, :update, :destroy]

    def index
      @task = Task.new
      show_uncompleted = Setting.last.show_uncompleted_todos 
    
      # 全てのタスクまたは完了したタスクを取得
      tasks_query = show_uncompleted ? Task.all : Task.where(completed: true)
    
      # 日付ごとにタスクをグループ化し、ページネーションを適用
      @tasks_by_date = tasks_query.group_by { |task| task.created_at.to_date }
      @paginated_tasks = Kaminari.paginate_array(@tasks_by_date.to_a).page(params[:page]).per(2)
    
      # 今日のタスクのリストを取得
      start_of_day = Date.today.beginning_of_day
      end_of_day = Date.today.end_of_day
      # タスクの取得と並び替え
      @tasks = Task.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day).order(created_at: :asc)

    end
    
    
    


    def new
        @task = Task.new
        @today_tasks = Task.where(deadline: Date.today)
    end

    def create
        @task = Task.new(task_params)
      
        # 今日の日付でフィルタリング
        start_of_day = Date.today.beginning_of_day
        end_of_day = Date.today.end_of_day
      
        # 今日作成されたタスクの数をカウント
        if Task.where(created_at: start_of_day..end_of_day).count < 10
          if @task.save
            redirect_to tasks_url, notice: 'タスクが追加されました。'
          else
            render :new
          end
        else
          redirect_to tasks_url, alert: '本日のタスク数が上限に達しています。'
        end
    end

    def edit
    end

    def update
        if @task.update(task_params)
            redirect_to tasks_path
        else 
            render :edit
        end
    end

    def destroy
        @task.destroy
        redirect_to tasks_path
    end

    def destroy_by_date
      date = params[:date].to_date
      Task.where('created_at >= ? AND created_at < ?', date.beginning_of_day, date.end_of_day).destroy_all
      redirect_to tasks_path, notice: '指定日付のタスクが削除されました。'
    end
    

    def complete
        @task = Task.find(params[:id])
        @task.update(completed: true, completion_date: Date.today)
    
        respond_to do |format|
          format.html { redirect_to tasks_url }
          format.js   # JavaScriptのレスポンスを扱う
        end
    end

    def past_tasks
      @show_uncompleted = Setting.last.show_uncompleted_todos
    
      # 昨日より前のタスクを古い順に取得
      tasks_query = if @show_uncompleted
                      Task.where('created_at < ?', Date.yesterday.beginning_of_day).order(created_at: :asc)
                    else
                      Task.where(completed: true).where('created_at < ?', Date.yesterday.beginning_of_day).order(created_at: :asc)
                    end
    
      # タスクを日付ごとにグループ化
      grouped_tasks = tasks_query.group_by { |task| task.created_at.to_date }
    
      # グループ化されたタスクを新しい日付順に並べ替える
      @tasks_by_date_paginated = Kaminari.paginate_array(grouped_tasks.to_a.sort_by { |date, _tasks| -date.to_time.to_i }).page(params[:page]).per(1)
    end
    
    
    
  

    private
    
    def task_params
        params.require(:task).permit(:title, :content, :completed)
    end

    def set_task
        @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def background_image_style(theme_name)
    image_url = case theme_name
                when 'プリンセス'
                  asset_path('princess_background.jpg')
                when '恐竜'
                  asset_path('dinosaur_background.jpg')
                else
                  asset_path('default_background.jpg')
                end

    "background: url(#{image_url}) no-repeat center center; background-size: cover;"
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/edit.html.erb
<div class="page-title">
  <h1>コメントを編集する</h1>
</div>
<%= form_with(model: @comment, url: comment_path(@comment), method: :patch) do |form| %>
  <div class="input-button-container">
    <div class="input-container">
      <%= form.label :comment, 'コメント', id: "comment-label" %>
      <%= form.text_area :comment, id: "comment-text-area" %>
      <%= form.submit "更新する" %>
    </div>
  </div>
<% end %>

app/views/comments/new.html.erb
<div class="page-title">
  <h1>コメントを書く</h1>
</div>
<%= form_with(model: @comment, url: comments_path) do |form| %>
  <%#  隠しフィールドは、ユーザーには見えないが、フォームが送信される際にデータとして送信される  %>
  <%= form.hidden_field :date %>
  <div class="input-button-container">
    <div class="input-container">
      <%= form.label  :comment , 'コメント' %>
      <%= form.text_area :comment %>
      <%= form.submit "コメントを保存" %>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyKidsTodo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body style="<%= background_image_style(@setting.display_background) %>">
    <header>
      <div class="header-container">
        <div class="header-title"><%= link_to 'Kids Todo App', root_path %></div>
        <nav>
          <%= link_to '📝きょうのやること', root_path %>
          <%= link_to '📖これまでのやること', past_tasks_tasks_path %>
          <%= link_to '設定', settings_path %>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/settings/edit.html.erb
<div class="page-title">
  <h1>設定を編集</h1>
</div>
<%= form_with(model: @setting, url: settings_path, method: :patch) do |form| %>
  <div class="settings-container">
    <% (1..10).each do |i| %>
      <div class="setting-item">
        <%= form.label "reward_url#{i}", "報酬 URL #{i}" %>
        <%= form.text_field "reward_url#{i}", placeholder: @setting.send("reward_url#{i}") %>
      </div>
    <% end %>
    <div class="setting-item">
      <%= form.label :show_uncompleted_todos, "未完了のTODOを表示" %>
      <%= form.check_box :show_uncompleted_todos %>
    </div>
    <div class="setting-item">
      <%= form.label :display_background, "背景表示" %>
      <%= form.select :display_background, ['初期設定', 'プリンセス', '恐竜'], {}, { class: "form-control" } %>
    </div>
  </div>
  <div class="edit-return-buttons">
    <%= form.submit "更新", class: "save-button" %>
    <%= link_to 'キャンセル', settings_path, class: "cancel-button" %>
  </div>
<% end %>

app/views/settings/show.html.erb
<div class="page-title">
  <h1>設定</h1>
</div>
<div class="settings-container">
  <% (1..10).each do |i| %>
    <div class="setting-item">
      <label>報酬 URL <%= i %></label>
      <p><%= @setting.send("reward_url#{i}") %></p>
    </div>
  <% end %>
  <div class="setting-item">
    <label>未完了のTODOを表示</label>
    <p><%= @setting.show_uncompleted_todos ? 'はい' : 'いいえ' %></p>
  </div>
  <div class="setting-item">
    <label>背景表示</label>
    <p><%= @setting.display_background %></p>
  </div>
</div>
<div class="edit-return-buttons">
  <%= link_to '編集', edit_settings_path, class: "edit-button", onclick: 'return mathChallenge()' %>
  <%= link_to '戻る', root_path, class: "return-button" %>
</div>

app/views/tasks/complete.js.erb
document.getElementById('task_<%= @task.id %>').classList.add('completed');

app/views/tasks/edit.html.erb
<div class="page-title">
  <h1>やることをかえる</h1>
</div>
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-container">
    <div class="field">
      <%= form.label "やること" %><br>
      <%= form.text_field :title %>
    </div>
  </div>
  <div class="field">
    <%= form.label :completed, '完了' %>
    <%= form.check_box :completed %>
  </div>
  <div class="actions">
    <%= form.submit "更新" %>
  </div>
<% end %>
<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<div class="page-title">
  <h1>📝きょうのやること</h1>
</div>
<%# タスクを作成 %>
<% start_of_day = Date.today.beginning_of_day %>
<% end_of_day = Date.today.end_of_day %>
<% if Task.where(created_at: start_of_day..end_of_day).count < 10 %>
  <%= form_with(model: @task, local: true) do |form| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="input-button-container">
      <div class="input-container">
        <%= form.label "やること" %>
        <%= form.text_field :title %>
        <%= form.submit "きめる" %>
      </div>
    </div>
  <% end %>
<% else %>
  <p>きょうのやることは10こあるよ！これくらいにしておこう！</p>
<% end %>
<%# settingsからご褒美URLを取得 %>
<% reward_urls = Setting.first.attributes.values_at(
  "reward_url1", "reward_url2", "reward_url3", "reward_url4", "reward_url5",
  "reward_url6", "reward_url7", "reward_url8", "reward_url9", "reward_url10"
) %>
<%# タスクリストを展開 %>
<% if @tasks.present? %>
  <div class="inner-tasklist">
    <ul>
      <% @tasks.each_with_index do |task, index| %>
        <li id="task_<%= task.id %>">
          <div class="inner-task">
            <h2 class="<%= 'completed' if task.completed %>"><%= task.title %></h2>
            <div class="compete-edit-delete-wrapper">
              <% if task.completed %>
                <% if reward_urls[index] %>
                  <%= link_to "ごほうび", reward_urls[index], target: "_blank", class: "reward-link" %>
                <% else %>
                  <div class="competed-text">ごほうび</div>
                <% end %>
              <% else %>
                <%= button_to "できた", complete_task_path(task), method: :put, remote: true, class: "complete-task-button" %>
              <% end %>
              <%= link_to "かえる", edit_task_path(task), class: "link-change-button" %>
              <%= button_to "けす", task_path(task), method: :delete, class: "link-delete-button" %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/past_tasks.erb
<h1>📖これまでのやること</h1>
<% if @tasks_by_date_paginated.present? %>
  <%= paginate @tasks_by_date_paginated %>
  <div class="inner-tasklist">
    <% @tasks_by_date_paginated.each do |date, tasks| %>
      <h2><%= date %></h2>
      <% comment = Comment.find_by(date: date) %>
      <p><%= comment&.comment || 'コメントはまだありません。' %></p>
      <% if comment %>
        <%= link_to 'コメントを編集', edit_comment_path(comment) %>
      <% else %>
        <%= link_to 'コメントを追加', new_comment_path(date: date) %>
      <% end %>
      <ul>
        <% tasks.each do |task| %>
          <% if @show_uncompleted || task.completed %>
            <li>
              <div class="inner-task">
                <h3 class="<%= 'completed' if task.completed %>"><%= task.title %></h3>
                <%= task.content %>
                <% if task.completed %>
                  <span class="status-label">😄できた</span>
                <% else %>
                  <span class="status-label">🥶できなかった</span>
                <% end %>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
  <%= paginate @tasks_by_date_paginated %>
<% end %>

app/views/tasks/past_tasks.html.erb
<div class="page-title">
  <h1>📖これまでのやること</h1>
</div>
<% if @tasks_by_date_paginated.present? %>
  <div class="paginate">
    <%= paginate @tasks_by_date_paginated %>
  </div>
  <div class="inner-tasklist">
    <% @tasks_by_date_paginated.each do |date, tasks| %>
      <div class="date-task-container">
        <div class="date-and-delete">
          <h2>-----------------------　<%= date %>　のやること　-----------------------</h2>
          <% comment = Comment.find_by(date: date) %>
        </div>
        <ul>
          <% tasks.each do |task| %>
            <% if @show_uncompleted || task.completed %>
              <li>
                <div class="inner-task">
                  <h3 class="<%= 'completed' if task.completed %>"><%= task.title %></h3>
                  <%= task.content %>
                  <% if task.completed %>
                    <span class="status-label">😄できた</span>
                  <% else %>
                    <span class="status-label">🥶できなかった</span>
                  <% end %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
        <div class="comment-container">
          <% if comment&.comment %>
            <span class="comment-emoji">😄</span> <span class="date-comment"><%= comment.comment %></span>
          <% else %>
            <span class="comment-emoji">👀</span> <span class="date-comment">コメントはまだありません。</span>
          <% end %>
        </div>
        <div class="comment-container">
          <% if comment %>
            <%= link_to 'コメントを編集', edit_comment_path(comment) , class: 'small-edit-button'%>
            <%= button_to 'コメントを削除', comment_path(comment),  class: 'small-delete-button',method: :delete, data: { confirm: 'このコメントを削除します。よろしいですか？' } %>
          <% else %>
            <%= link_to 'コメントを追加', new_comment_path(date: date) , class: 'small-edit-button'%>
          <% end %>
        </div>
        <div class="date-and-delete">
          <h2>-------------------------------------------------------------------------------------</h2>
        </div>
        <div class="date-and-delete">
          <%= button_to "この日のタスクを消す", destroy_by_date_tasks_path(date: date), method: :delete, data: { confirm: 'この日に作成された全タスクを削除します。よろしいですか？' } , class: 'small-delete-button'%>
        </div>
      <% end %>
    </div>
  </div>
<% end %>